events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        # We will copy the 'out' directory to /usr/share/nginx/html/blog
        # So the root should be /usr/share/nginx/html
        root /usr/share/nginx/html;
        
        index index.html;

        # Handle requests. Since basePath is /blog, most requests will start with /blog
        location / {
            try_files $uri $uri.html $uri/ =404;
        }
        
        # Redirect root to /blog if desired, or just let it 404 if no index.html at root
        location = / {
            return 301 /blog;
        }

        # Force content-type for opengraph-image
        location = /blog/opengraph-image {
            default_type image/png;
        }
    }
}
